### ISSUE TITLE
Blobs are not being sent out

### ISSUE THREAD

**Issue by boreq** [planetary-social/planetary-ios#1190]
Talk to @danlatorre. 

Findings:
- Feed `@GCSmjLHmFC8m9t0ouJ6cY4tzlQdIbBaQfI0Uifw5cZA=.ed25519`
- Message `%nIm6mtgphEpGNCSOCeTqcNoyJdgLHYVqtyXf5yUhaLI=.sha256`
- Blob `&8g+5yZBABNQFvaqBqivv++eH67paBYuV/NtArRkB6t4=.sha256`
- Message is valid, everything looks correct.
- hex of the blob's hash is `f20fb9c9904004d405bdaa81aa2beffbe787ebba5a058b95fcdb40ad1901eade`
- blob is correctly stored
```
$ find . -iname "0fb9c9904004d405bdaa81aa2beffbe787ebba5a058b95fcdb40ad1901eade"
./GoSbot/blobs/sha256/f2/0fb9c9904004d405bdaa81aa2beffbe787ebba5a058b95fcdb40ad1901eade
```
- we sent out has
```
gobot-2023-02-22_14-25.log:time="2023-02-22 14:26:05.3714790 (UTC)" level=debug msg="sending want or has" name=scuttlego.wants_process num_incoming=1 source=golang v="<id=&8g+5yZBABNQFvaqBqivv++eH67paBYuV/NtArRkB6t4=.sha256 size=124362>"
```

- we received an error
```
time="2023-02-23 14:18:26.9087784 (UTC)" level=trace msg="received a message" body="{\"message\":\"Unexpected token � in JSON at position 0\",\"name\":\"SyntaxError\",\"stack\":\"SyntaxError: Unexpected token � in JSON at position 0\\n    at JSON.parse (<anonymous>)\\n    at decodeBody (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/secret-stack/node_modules/packet-stream-codec/index.js:74:49)\\n    at Object.cb (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/secret-stack/node_modules/packet-stream-codec/index.js:107:13)\\n    at drain (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/pull-reader/index.js:39:14)\\n    at more (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/pull-reader/index.js:55:13)\\n    at /Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/pull-reader/index.js:66:9\\n    at /Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/pull-inactivity/node_modules/pull-abortable/index.js:38:11\\n    at /Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/pull-stream/throughs/through.js:19:9\\n    at Object.cb (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/pull-box-stream/index.js:141:11)\\n    at drain (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/pull-reader/index.js:39:14)\"}" ctx.connection_id=6 ctx.peer_id="qFtLJ6P5Eh9vKxnj7Rsh8SkE6B6Z36DVLP7ZOKNeQ/Y=" header.bodyLength=1287 header.flags="<stream=true endOrError=true bodyType={json}>" header.number=-3 name=scuttlego.raw
```
- it is not lupus, this is most likely https://github.com/planetary-social/scuttlego/issues/9.

**Comment by boreq** [comment]
For context the blobs were getting out during my testing because they were being sent to scuttlego which ignores message body type completely... after all you have to know what body type it is to parse it anyway so what is the point of looking at that field. The JS stack seems to be parsing all messages with JSON type as JSON because it is something you can easily do in JS.

**Comment by boreq** [comment]
Fixed in TestFlight 405.
