### ISSUE TITLE
scuttlego bindings: method:invite,use is not in list of allowed methods

### ISSUE THREAD

**Issue by boreq** [planetary-social/planetary-ios#955]
```
ssbInviteAccept error {"message":"method:invite,use is not in list of allowed methods","name":"Error","stack":"Error: method:invite,use is not in list of allowed methods\n    at Function.perms.pre (/home/node/node_modules/muxrpc/permissions.js:88:14)\n    at Object.<anonymous> (/home/node/node_modules/muxrpc/local-api.js:35:21)\n    at Object.request (/home/node/node_modules/muxrpc/stream.js:48:17)\n    at PacketStream._onrequest (/home/node/node_modules/packet-stream/index.js:161:17)\n    at PacketStream.write (/home/node/node_modules/packet-stream/index.js:134:41)\n    at /home/node/node_modules/muxrpc/pull-weird.js:56:15\n    at /home/node/node_modules/pull-stream/sinks/drain.js:24:37\n    at /home/node/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11\n    at Object.cb (/home/node/node_modules/packet-stream-codec/index.js:111:11)\n    at drain (/home/node/node_modules/pull-reader/index.js:39:14)"}
level=error ts="2022-11-10 16:13:39.7550750 (UTC)" source=golang function=ssbInviteAccept error="command failed: could not contact the pub and redeem the invite: received an error: remote returned an error"
```

**Comment by boreq** [comment]
I think there is no bug here, there was something wrong with the invites and this was misdiagnosed.
